### ISSUE TITLE
How to Select multiple CAN database?

### ISSUE THREAD

**Issue by BCGelandwagen** [PlotJuggler/plotjuggler-CAN-dbs#17]
Is there a way to load multiple CAN database and plot them on different CAN channels? I have a 2 channel peak can tool but I have to open two instances of PJ and load a SAE and a custom .dbc files to see the graphs. 

I am using the AppImage of PlotJuggler (v3.7.1), which btw is super helpful since I was not able to compile the linux version on my machine. Thank you for that.

**Comment by ozzdemir** [comment]
It's nice to hear the release is useful.

Loading multiple instances of plugins is required since a single plugin can only attach to a single can channel. So, this is not a plugin issue but a main app one. Previously, I had similar requirements that I had mentioned in https://github.com/facontidavide/PlotJuggler/issues/451 and also worked on tackling it myself (with some PoC results), but I couldn't invest much time to create a clean PR.

I still want to work on that, but I am unsure about its timeline.

If it is possible to evaluate the signals later on, i.e. you are not working on tuning some variables and observing the results; I can recommend the following as a workaround.

- Record the channels individually using candump and using DataLoadCAN to load the recorded CAN logs one by one. This way, you can plot signals from both channels using different databases and compare them.

**Comment by BCGelandwagen** [comment]
Thanks ozzdemir. I did find a work around that allows me to merge two dbc files together, and able to load the merged dbc file in PJ and use only one can channel and plot them together. it's quite useful. For anyone who's interested the link is: https://github.com/ebroecker/canmatrix/blob/development/docs/cli.rst
`$ canconvert --merge=second.dbc source.dbc target.dbc`
